"""Add starter code fields per language

Revision ID: 1261a630a9e8
Revises: 
Create Date: 2025-06-17 13:23:31.168966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1261a630a9e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('python_starter_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cpp_starter_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('java_starter_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('javascript_starter_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c_starter_code', sa.Text(), nullable=True))
        batch_op.drop_column('starter_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starter_code', sa.TEXT(), nullable=False))
        batch_op.drop_column('c_starter_code')
        batch_op.drop_column('javascript_starter_code')
        batch_op.drop_column('java_starter_code')
        batch_op.drop_column('cpp_starter_code')
        batch_op.drop_column('python_starter_code')

    # ### end Alembic commands ###
