"""Add language-specific function_signature and driver_code

Revision ID: 636d84a2b590
Revises: 1261a630a9e8
Create Date: 2025-06-17 18:16:17.877858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636d84a2b590'
down_revision = '1261a630a9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('python_function_signature', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('cpp_function_signature', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('java_function_signature', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('javascript_function_signature', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('c_function_signature', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('python_driver_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cpp_driver_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('java_driver_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('javascript_driver_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c_driver_code', sa.Text(), nullable=True))
        batch_op.drop_column('function_signature')
        batch_op.drop_column('driver_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_code', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('function_signature', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('c_driver_code')
        batch_op.drop_column('javascript_driver_code')
        batch_op.drop_column('java_driver_code')
        batch_op.drop_column('cpp_driver_code')
        batch_op.drop_column('python_driver_code')
        batch_op.drop_column('c_function_signature')
        batch_op.drop_column('javascript_function_signature')
        batch_op.drop_column('java_function_signature')
        batch_op.drop_column('cpp_function_signature')
        batch_op.drop_column('python_function_signature')

    # ### end Alembic commands ###
