"""Remove Java, JS, C fields from Problem

Revision ID: bc672636618c
Revises: 636d84a2b590
Create Date: 2025-06-21 16:33:58.181521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc672636618c'
down_revision = '636d84a2b590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('java_function_signature')
        batch_op.drop_column('c_starter_code')
        batch_op.drop_column('javascript_driver_code')
        batch_op.drop_column('javascript_starter_code')
        batch_op.drop_column('c_driver_code')
        batch_op.drop_column('c_function_signature')
        batch_op.drop_column('javascript_function_signature')
        batch_op.drop_column('java_starter_code')
        batch_op.drop_column('java_driver_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('java_driver_code', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('java_starter_code', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('javascript_function_signature', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('c_function_signature', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('c_driver_code', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('javascript_starter_code', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('javascript_driver_code', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('c_starter_code', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('java_function_signature', sa.VARCHAR(length=300), nullable=True))

    # ### end Alembic commands ###
